apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: employee-crud-cluster
  region: us-east-2

vpc:
  id: vpc-04af69411e0dfc0fb
  cidr: "192.168.0.0/16"
  subnets:
    public:
      ec-stack-PublicSubnet01:
        id: subnet-050a7e8494e2c04e6
      ec-stack-PublicSubnet02:
        id: subnet-0e21ec0ad64bb3589
    private:
      ec-stack-PrivateSubnet01:
        id: subnet-0d2bbfb0b9d20cbba
      ec-stack-PrivateSubnet02:
        id: subnet-049c66fccab969973

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true