apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: Employee-Crud-Cluster
  region: us-east-2

vpc:
  id: vpc-030ebeee77bed4556
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-0c62d7a3b4ca463e8
      my-new-stack-PublicSubnet02:
        id: subnet-09311934c24cf2cb4
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-0ed3cdd3f2b37c549
      my-new-stack-PrivateSubnet02:
        id: subnet-0bb57546525e3737f

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true