apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: employee-crud-cluster
  region: us-east-2

vpc:
  id: vpc-0bb9f002ab10354fa
  cidr: "192.168.0.0/16"
  subnets:
    public:
      ec-stack-PublicSubnet01:
        id: subnet-02f2d908e783b359a
      ec-stack-PublicSubnet02:
        id: subnet-0646bd6166ff13c58
    private:
      ec-stack-PrivateSubnet01:
        id: subnet-0df6350f51f88d282
      ec-stack-PrivateSubnet02:
        id: subnet-078791badb48d2f93

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true